Models/AgenciesChangeState.cs
namespace EmergencyDashboard.Models
{
    public class AgenciesChangeState
    {
        public int AgencyId { get; set; }
        public string State { get; set; } = null!;
    }
}

Models/AgenciesModel.cs
namespace EmergencyDashboard.Models
{
    public class AgenciesModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Status { get; set; }
        public string City { get; set; }
    }
}

Models/Reports.cs
namespace EmergencyDashboard.Models
{
    public class Reports
    {
        public int Id { get; set; }
        public string Name { get; set; } = null!;
        public string Address { get; set; } = null!;
        public string City { get; set; } = null!;
        public string Type { get; set; } = null!;
        public string Time { get; set; } = null!;
        public string Status { get; set; } = null!;
    }
}

Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

using System.Diagnostics;

namespace EmergencyDashboard.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Pages/Index.cshtml.cs
using EmergencyDashboard.Hubs;
using EmergencyDashboard.Models;

using Microsoft.AspNetCore.Mvc;

namespace EmergencyDashboard.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;
        private MainContext _context;
        private readonly IHubContext<MainHub> mainHub;
        public IEnumerable<AgenciesModel> Agencies { get; set; } = null!;
        public IEnumerable<Reports> Reports { get; set; } = null!;

        public IndexModel(ILogger<IndexModel> logger, MainContext _context, IHubContext<MainHub> hubContext)
        {
            _logger = logger;
           mainHub = hubContext;
            this._context = _context;
        }

     public async Task OnGetAsync()
        {
            Agencies = await _context.Agencies.OrderBy(x => x.Id).ToListAsync();
            Reports = await _context.Reports.OrderBy(x => x.Id).ToListAsync();
        }
        public async Task OnPostStart()
        {
            await mainHub.Clients.All.SendAsync("ChangeStateTest", "Aktywna");
            Thread.Sleep(5000);
            await mainHub.Clients.All.SendAsync("ChangeStateTest", "Na wyjeździe");
        }
    }
}

Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace EmergencyDashboard.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

Pages/DataManipulation.cshtml
@page
@model EmergencyDashboard.Pages.DataManipulationModel
@{
}
<form method="post">
    <button type="submit" class="btn btn-sm btn-success" asp-page-handler="Start">Start show</button>
</form>

Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}<div class="grid-container">
    <div class="grid-item-header"><h1>Emergency Dashboard - najszybszy monitoring </h1></div>
    <div class="grid-item-agencies">
        <table class="table" id="agenciesTable">

            <thead>
                <tr>
                    <th scope="col">Jednostka </th>
                    <th scope="col">Miasto </th>
                    <th scope="col">Status </th>
                </tr>
            </thead>
            <tbody>
                 @foreach (var agency in Model.Agencies)
                {  
                <tr id="@agency.Id-liveCadSingleRow">
                <td>@agency.Name</td>
                <td>@agency.City</td>
                <td id="@agency.Id-stat">test</td>
                </tr>
                }
            </tbody>
        </table>
    </div>
    <div class="grid-item-counter"><h2><b>Liczba koordynatorów online w całej polsce: <span id="viewCounter">0</span></b></h2></div>
    <div class="grid-item-reports">
        <table class="table">
                 <thead>
                <tr>
                    <td>Jednostka</td>
                    <td>Miasto</td>
                    <td>Adres</td>
                    <td>Typ zgłoszenia</td>
                    <td>Czas zgłoszenia</td>
                    <td>Status</td>
                </tr>
            </thead>
            <tbody id="reportTable">
                @foreach (var report in Model.Reports)
                {
                    <tr id="@report.Id-liveCadReportRow">
                        <td >@report.Name</td>
                        <td >@report.City</td>
                        <td >@report.Address</td>
                        <td >@report.Type</td>
                        <td >@report.Time</td>
                        <td id="@report.Id-reportstate">@report.Status</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>
@section Scripts{
    <script src="~/js/signalr/dist/browser/signalr.js"></script>
    <script src="~/index.js" asp-append-version="true"></script>
}

Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Emergency Dashboard</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/EmergencyDashboard.styles.css" asp-append-version="true" />
</head>
<body>
@*    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">EmergencyDashboard </a>
                <a class="navbar-brand" asp-area="" asp-page="/DataManipulation">Admin Panel </a>
                <a class="navbar-brand" asp-area="" asp-page="#"></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
        </nav>
    </header>*@
@*    <div class="container">*@

            @RenderBody()

   @* </div>*@


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>